{% set name = "multiclean" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/multiclean-{{ version }}.tar.gz
  sha256: 0a65bd6aa4b07fd01ffb7ee3e287d57ae415ac5724e74d7ee2ff968edba333e2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - python >={{ python_min }}
    - opencv >=4.0
    - scipy >=1.0

test:
  imports:
    - multiclean
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}
    - libopencv * =*headless*  # [linux]

about:
  home: https://github.com/DPIRD-DMA/MultiClean
  description: Python library for morphological cleaning of multiclass 2D numpy arrays (edge smoothing and island removal)
  summary: Python library for morphological cleaning of multiclass 2D numpy arrays (edge smoothing and island removal)
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - giswqs
